/* =============================================
   María del Mar Blanquería — Datos compartidos
   ÚNICO lugar para editar productos, precios e imágenes
   ============================================= */

const WA_NUMBER = '91173607330';

const CAT_LABELS = {
  cama:          'Dormitorio',
  baño:          'Baño',
  almohadas:     'Almohadas',
  accesorios:    'Deco',
  lineainfantil: 'Línea Infantil',
  cocina:        'Cocina',
};

const SUBCAT_LABELS = {
  sabanas:    'Sábanas',
  frazadas:   'Frazadas',
  almohadas:  'Almohadas',
  acolchados: 'Acolchados',
};

const PRODUCTS = [
  {
    id: 1,
    cat: 'cama',
    subcat: 'sabanas',
    name: 'Juego de sábanas 2 1/2 plazas de algodón',
    desc: '100% algodón. Bajera, encimera y 2 fundas. Disponibles en color Verde Agua, Rosa Dior y Blancas.',
    features: [],
    price: '33.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: ['Verde Agua', 'Rosa Dior', 'Blanco'],
    images: [
      'assets/products/sabanas-4-piezas.jpeg',
      'assets/products/sabanas-4-piezas.jpg',
      'assets/products/sabanas-4-piezas-2.jpg',
      'assets/products/sabanas-4-piezas-3.jpg',
    ],
    hidden: false,
  },
  {
    id: 13,
    cat: 'cama',
    subcat: 'sabanas',
    name: 'Sabanas ajustables hoteleras. 2 plazas y 2 1/2 plazas',
    desc: '100% algodón. Varios colores disponibles.',
    features: [],
    price: '18.000',
    emoji: '🛏️',
    badge: 'promo',
    indications: '',
    colors: ['Azul marino', 'Beige', 'Blanco', 'Bordo', 'Gris', 'Celeste'],
    images: [
      'assets/products/sabanas-ajustables-hoteleras.jpg',
      'assets/products/sabanas-ajustables-hoteleras-2.jpg',
      'assets/products/sabanas-ajustables-hoteleras-3.jpg',
    ],
    hidden: false,
  },
  {
    id: 14,
    cat: 'cama',
    subcat: 'frazadas',
    name: 'Frazadas Goldsun de piel',
    desc: 'Frazadas de piel de 2 1/2 plazas, super abrigadas, ideales para el invierno. Varios colores disponibles.',
    features: [],
    price: '45.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: ['Blanco', 'Gris', 'Rosa', 'Azul'],
    images: [
      'assets/products/frazadas-goldsun.jpg',
      'assets/products/frazadas-goldsun-2.jpg',
    ],
    hidden: false,
  },
  {
    id: 2,
    cat: 'baño',
    name: 'Juego de Toallón y Toallas',
    desc: 'Set x3. 1 Toallón + 2 Toallas. Ultra absorbentes y de secado rápido.',
    features: [
      '1 Toallón de 140x70cm',
      '2 Toallas de 76x46cm',
    ],
    price: '26.000',
    emoji: '🛁',
    badge: 'new',
    indications: '',
    colors: ['Rosa', 'Beige', 'Gris', 'Blanco'],
    images: ['assets/products/juego-toallon-toallas.jpg'],
    hidden: false,
  },
  {
    id: 3,
    cat: 'cama',
    subcat: 'sabanas',
    name: 'Sabanas ajustables de algodón con elástico',
    desc: 'Estuche x4 unidades. 100% algodón.',
    features: [],
    price: '45.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: ['Azul', 'Blanco', 'Rosa', 'Gris', 'Verde Agua', 'Beige'],
    images: [
      'assets/products/sabanas-ajustables.jpg',
      'assets/products/sabanas-ajustables-2.jpg',
    ],
    hidden: false,
  },
  {
    id: 15,
    cat: 'cama',
    subcat: 'acolchados',
    name: 'Cover de verano 2 1/2 plazas',
    desc: 'Cubrecama de verano Goldsun, 2 1/2 plazas, liviano y fresco. Varios colores disponibles.',
    features: [],
    price: '28.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: ['Verde Agua', 'Rosa Dior', 'Blanco'],
    images: [
      'assets/products/cover-verano-goldsun.jpg',
      'assets/products/cover-verano-goldsun-2.jpg',
      'assets/products/cover-verano-goldsun-3.jpg',
      'assets/products/cover-verano-goldsun-4.jpg',
    ],
    hidden: true,
  },
  {
    id: 4,
    cat: 'cama',
    subcat: 'sabanas',
    name: 'Sabanas hoteleras bordadas',
    desc: 'Sabanas hoteleras bordadas, 100% algodón premium. Varios colores disponibles.',
    features: [],
    price: '47.000',
    emoji: '🛏️',
    badge: 'promo',
    indications: '',
    colors: [],
    images: [
      'assets/products/sabanas-hoteleras-bordadas.jpg',
      'assets/products/sabanas-hoteleras-bordadas-2.jpg',
    ],
    hidden: false,
  },
  {
    id: 26,
    cat: 'cama',
    subcat: 'sabanas',
    name: 'Juego de Sabanas 1 1/2 plazas',
    desc: 'Sabanas 1 1/2 plazas, 100% poliester. Varios colores disponibles',
    features: [
      '1 sabana plana: Medidas 160x240cm',
      '1 sabana ajustable: Medidas 90x190+25cm',
      '1 funda de almohada: Medidas 50x70cm',],
    price: '27.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: ['Bordo', 'Blanco', 'Marron Chocolate'],
    images: [
      'assets/products/sabanas-queen-size.jpg',
    ],
    hidden: false,
  },
  {
    id: 5,
    cat: 'baño',
    name: 'Alfombra de baño de silicona antideslizante',
    desc: 'Silicona antideslizante. Varios colores.',
    features: [],
    price: '6.500',
    emoji: '🛁',
    badge: 'new',
    indications: '',
    colors: [],
    images: ['assets/products/alfombra-bano.jpg'],
    hidden: false,
  },
  {
    id: 6,
    cat: 'baño',
    name: 'Cortina de baño teflonada con ganchos',
    desc: 'Cortina de baño teflonada en bolsa de tela + Ganchos. Diseños exclusivos.',
    features: [],
    price: '24.000',
    emoji: '🛁',
    badge: 'promo',
    indications: '',
    colors: [],
    images: [
      'assets/products/cortina-bano.jpg',
      'assets/products/cortina-bano-2.jpg',
      'assets/products/cortina-bano-3.jpg',
    ],
    hidden: false,
  },
  {
    id: 7,
    cat: 'cama',
    subcat: 'almohadas',
    name: 'Funda de almohada rayada de 600 hilos',
    desc: 'Fundas de algodón rayadas, varios colores disponibles.',
    features: [],
    price: '6.500',
    emoji: '🌼',
    badge: 'promo',
    indications: '',
    colors: ['Blanco', 'Gris', 'Rosa', 'Azul', 'Negro'],
    images: [
      'assets/products/fundas-almohadas-rayadas.jpg',
      'assets/products/fundas-almohadas-rayadas-2.jpg',
    ],
    hidden: false,
  },
  {
    id: 17,
    cat: 'cama',
    subcat: 'sabanas',
    name: 'Sabanas hoteleras bordado Inglés 2 1/2 plazas',
    desc: 'Sabanas bordadas con diseño inglés de algodón, 3800 hilos, varios colores disponibles.',
    features: [],
    price: '45.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: ['Blanco', 'Gris', 'Rosa', 'Beige'],
    images: [
      'assets/products/sabanas-bordado-ingles.jpg',
    ],
    hidden: false,
  },
  {
    id: 8,
    cat: 'baño',
    name: 'Cortina de baño, tela bambú con ganchos metálicos',
    desc: 'Cortina de baño de tela bambú + Ganchos metálicos. Diseños exclusivos.',
    features: [],
    price: '27.000',
    emoji: '🏖️',
    badge: 'new',
    indications: 'Lavar con agua tibia a menos de 30° con detergente sin iones, secar con maquina a menos de 30°',
    colors: ['Beige claro', 'Negro', 'Beige tostado'],
    images: [
      'assets/products/cortina-bano-bambu.jpg',
      'assets/products/cortina-bano-bambu-2.jpg',
      'assets/products/cortina-bano-bambu-3.jpg',
    ],
    hidden: false,
  },
  {
    id: 18,
    cat: 'cama',
    subcat: 'sabanas',
    name: 'Sábanas Super King - 3800 hilos',
    desc: 'Sábanas Super King de algodón premium, 3800 hilos. Suavidad y durabilidad excepcional.',
    features: [
      '1 pieza de sábana: Medidas 230x270cm',
      '1 pieza cubre colchón: Medidas 200x203cm',
      '2 piezas de funda: Medidas 57x82cm',
    ],
    price: '55.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: [],
    images: [
      'assets/products/sabanas-casa-mundo.jpg',
    ],
    hidden: false,
  },
  {
    id: 19,
    cat: 'cama',
    subcat: 'sabanas',
    name: 'Juego de Sábanas Hoteleras - Tamaño Queen',
    desc: 'Sabanas Hoteleras de algodón premium, 2500 hilos. Suavidad y durabilidad excepcional.',
    features: [
      '1 pieza de sábana: Medidas 230x250cm',
      '1 pieza cubre colchón: Medidas 160x200+35cm',
      '2 piezas de fundas: Medidas 51x76cm',
    ],
    price: '45.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: [],
    images: [
      'assets/products/sabanas-lujosas-queen.jpg',
      'assets/products/sabanas-lujosas-queen-2.jpg',
    ],
    hidden: false,
  },
   // ---------- Deco ----------
{
    id: 20,
    cat: 'deco',
    subcat: 'Alfombras',
    name: 'Alfombras Shaggy',
    desc: 'Alfombras Shaggy de alta calidad, perfectas para dar un toque de estilo a tu hogar. Varios colores disponibles',
    features: ['Medidas: 40x60cm'],
    price: '10.000',
    emoji: '🛏️',
    badge: 'promo',
    indications: '',
    colors: ["Marron", "Rojo", "Azul", "Gris", "Blanco", "Beige"],
    images: [
      'assets/products/alfombras-shaggy.jpg',
      'assets/products/alfombras-shaggy-2.jpg',
      'assets/products/alfombras-shaggy-3.jpg',
    ],
    hidden: false,
  },
  {
    id: 21,
    cat: 'deco',
    subcat: 'Alfombras',
    name: 'Alfombras Piel de Conejo',
    desc: 'Alfombras Piel de Conejo de alta calidad para darle un toque de estilo a tu habitación. Varios colores disponibles',
    features: ['Medidas: 40x60cm'],
    price: '20.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: ["Beige", "Blanco"],
    images: [
      'assets/products/alfombra-piel-conejo.jpg',
    ],
    hidden: false,
  },
{
    id: 22,
    cat: 'deco',
    subcat: 'Alfombras',
    name: 'Tapete felpudo',
    desc: 'Tapete felpudo de alta calidad. Varios colores disponibles',
    features: ['Medidas: 40x60cm'],
    price: '13.000',
    emoji: '🛏️',
    badge: 'promo',
    indications: '',
    colors: ["Gris", "Blanco", "Salmón"],
    images: [
      'assets/products/tapete-felpudo.jpg',
    ],
    hidden: false,
  },
{
    id: 23,
    cat: 'deco',
    subcat: 'Alfombras',
    name: 'Pie de cama',
    desc: 'Pie de cama, 100% algodón. Varios colores disponibles',
    features: ['Medidas: 40x60cm'],
    price: '22.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: ["Dulce de leche", "Blanco", "Verde Oliva"],
    images: [
      'assets/products/pie-de-cama.jpg',
      'assets/products/pie-de-cama-2.jpg',
      'assets/products/pie-de-cama-3.jpg',
      'assets/products/pie-de-cama-4.jpg',
    ],
    hidden: false,
  },
  {
    id: 24,
    cat: 'deco',
    subcat: 'Alfombras',
    name: 'Alfombra memoria lisa',
    desc: 'Alfombra con memoria, ideal para el dormitorio. 100% de poliester.',
    features: ['Medidas: 40x60cm'],
    price: '13.000',
    emoji: '🛏️',
    badge: 'new',
    indications: '',
    colors: [],
    images: [
      'assets/products/alfombra-pies.jpg',
    ],
    hidden: false,
  },
  {
    id: 25,
    cat: 'deco',
    subcat: 'Alfombras',
    name: 'Camino de mesa',
    desc: 'Camino de mesa, 100% de lino.',
    features: ['Medidas: 150x42cm'],
    price: '12.000',
    emoji: '🛏️',
    badge: 'promo',
    indications: '',
    colors: [],
    images: [
      'assets/products/camino-de-mesa.jpg',
      'assets/products/camino-de-mesa-2.jpg'
    ],
    hidden: false,
  },

  // ---------- Cocina ----------
  {
    id: 9,
    cat: 'cocina',
    name: 'Delantal de cocina',
    desc: 'Delantal de cocina resistente y lavable. Varios diseños y colores disponibles.',
    features: [],
    price: '19.000',
    emoji: '👨‍🍳',
    badge: 'new',
    indications: '',
    colors: [],
    images: [
      'assets/products/delantal-cocina.jpg',
      'assets/products/delantal-cocina-2.jpg',
      'assets/products/delantal-cocina-3.jpg',
      'assets/products/delantal-cocina-4.jpg',
    ],
    hidden: false,
  },
  {
    id: 10,
    cat: 'cocina',
    name: 'Mantel antimanchas',
    desc: 'Mantel antimanchas, diseño 100% de poliester, fácil de lavar.',
    features: [],
    price: '20.000',
    emoji: '🧺',
    badge: 'new',
    indications: '',
    colors: [],
    images: [
      'assets/products/mantel-antimanchas.jpg',
      'assets/products/mantel-antimanchas-2.jpg',
      'assets/products/mantel-antimanchas-3.jpg',
    ],
    hidden: false,
  },
  {
    id: 16,
    cat: 'cocina',
    name: 'Repasadores de cocina colgantes',
    desc: 'Repasadores colgantes, hermosos diseños de frutas ideales para decorar tu cocina. 100% algodón.',
    features: [],
    price: '6.000',
    emoji: '🧺',
    badge: 'new',
    indications: '',
    colors: [],
    images: [
      'assets/products/repasadores-frutas.jpg',
      'assets/products/repasadores-frutas-2.jpg',
      'assets/products/repasadores-frutas-3.jpg',
      'assets/products/repasadores-frutas-4.jpg',
    ],
    hidden: false,
  },
  // ---------- Línea Infantil ----------
  {
    id: 11,
    cat: 'lineainfantil',
    name: 'Sábanas infantiles en mochila — Línea Disney',
    desc: 'Juego de sábanas infantiles en mochila. Diseños Disney. Ideal para regalo.',
    features: [],
    price: '30.000',
    emoji: '🧸',
    badge: 'new',
    indications: '',
    colors: [],
    images: [
      'assets/products/sabanas-infantiles.jpg',
      'assets/products/sabanas-infantiles-2.jpg',
    ],
    hidden: true,
  },
  {
    id: 12,
    cat: 'lineainfantil',
    name: 'Frazadas Flannel infantiles',
    desc: 'Frazadas de flannel suaves y abrigadas. Varios diseños y colores para los más chiquitos.',
    features: [],
    price: '22.000',
    emoji: '🌟',
    badge: 'new',
    indications: '',
    colors: [],
    images: [
      'assets/products/sabanas-infantiles-flannel.jpg',
      'assets/products/sabanas-infantiles-flannel-2.jpg',
      'assets/products/sabanas-infantiles-flannel-3.jpg',
      'assets/products/sabanas-infantiles-flannel-4.jpg',
      'assets/products/sabanas-infantiles-flannel-5.jpg',
    ],
    hidden: true,
  },
];

// ⚠️ Último ID usado: 26 — el próximo producto debe ser id: 27