/* =============================================
   María del Mar Blanquería — Datos compartidos
   ÚNICO lugar para editar productos, precios e imágenes
   ============================================= */

const WA_NUMBER = '91173607330';

const CAT_LABELS = {
  cama:          'Ropa de cama',
  baño:          'Baño',
  almohadas:     'Almohadas',
  accesorios:    'Accesorios',
  lineainfantil: 'Línea Infantil',
  cocina:        'Cocina',
};

const PRODUCTS = [
  {
    id: 1,
    cat: 'cama',
    name: 'Juego de sábanas 2 1/2 plazas de algodón',
    desc: '100% algodón. Bajera, encimera y 2 fundas. Disponibles en color Verde Agua, Rosa Dior y Blancas.',
    price: '33.000',
    emoji: '🛏️',
    badge: 'new',
    indications:'',
    images: [
      'assets/products/sabanas-4-piezas.jpeg',
      'assets/products/sabanas-4-piezas.jpg',
      'assets/products/sabanas-4-piezas-2.jpg',
      'assets/products/sabanas-4-piezas-3.jpg',
    ],
  },
  {
    id: 13,
    cat: 'cama',
    name: 'Sabanas ajustables hoteleras. 2 plazas y 2 1/2 plazas',
    desc: '100% algodón. Varios colores disponibles.',
    price: '18.000',
    emoji: '🛏️',
    badge: 'promo',
    indications:'',
    images: [
      'assets/products/sabanas-ajustables-hoteleras.jpg',
      'assets/products/sabanas-ajustables-hoteleras-2.jpg',
      'assets/products/sabanas-ajustables-hoteleras-3.jpg',
    ],
  },
  {
    id: 14,
    cat: 'cama',
    name: 'Frazadas Goldsun de piel',
    desc: 'Frazadas de piel de 2 1/2 plazas, super abrigadas, ideales para el invierno. Varios colores disponibles.',
    price: '45.000',
    emoji: '🛏️',
    badge: 'new',
    indications:'',
    images: [
      'assets/products/frazadas-goldsun.jpg',
      'assets/products/frazadas-goldsun-2.jpg',
    ],
  },
  {
    id: 2,
    cat: 'baño',
    name: 'Juego de Toallón y Toallas',
    desc: 'Set x3. 1 Toallón de 140x70cm + 2 Toallas de 76x46cm. Ultra absorbentes y de secado rápido.',
    price: '26.000',
    emoji: '🛁',
    badge: 'new',
    indications:'',
    images: ['assets/products/juego-toallon-toallas.jpg'],
  },
  {
    id: 3,
    cat: 'cama',
    name: 'Sabanas ajustables de algodón con elástico',
    desc: 'Estuche x4 unidades. 100% algodón.',
    price: '45.000',
    emoji: '🛏️',
    badge: 'new',
    indications:'',
    images: [
      'assets/products/sabanas-ajustables.jpg',
      'assets/products/sabanas-ajustables-2.jpg',
    ],
  },
  {
    id: 15,
    cat: 'cama',
    name: 'Cover de verano 2 1/2 plazas',
    desc: 'Cubrecama de verano Goldsun, 2 1/2 plazas, liviano y fresco. Varios colores disponibles.',
    price: '28.000',
    emoji: '🛏️',
    badge: 'new',
    indications:'',
    images: [
      'assets/products/cover-verano-goldsun.jpg',
      'assets/products/cover-verano-goldsun-2.jpg',
      'assets/products/cover-verano-goldsun-3.jpg',
      'assets/products/cover-verano-goldsun-4.jpg',
    ],
  },
  {
    id: 4,
    cat: 'cama',
    name: 'Sabanas hoteleras bordadas',
    desc: 'Sabanas hoteleras bordadas, 100% algodón premium. Varios colores disponibles.',
    price: '47.000',
    emoji: '🛏️',
    badge: 'promo',
    indications:'',
    images: [
      'assets/products/sabanas-hoteleras-bordadas.jpg',
      'assets/products/sabanas-hoteleras-bordadas-2.jpg',
    ],
  },
  {
    id: 5,
    cat: 'baño',
    name: 'Alfombra de baño de silicona antideslizante',
    desc: 'Silicona antideslizante. Varios colores.',
    price: '6.500',
    emoji: '🛁',
    badge: 'new',
    indications:'',
    images: ['assets/products/alfombra-bano.jpg'],
  },
  {
    id: 6,
    cat: 'baño',
    name: 'Cortina de baño teflonada con ganchos',
    desc: 'Cortina de baño teflonada en bolsa de tela + Ganchos. Diseños exclusivos.',
    price: '24.000',
    emoji: '🛁',
    badge: 'promo',
    indications:'',
    images: [
      'assets/products/cortina-bano.jpg',
      'assets/products/cortina-bano-2.jpg',
      'assets/products/cortina-bano-3.jpg',
    ],
  },
  {
    id: 7,
    cat: 'cama',
    name: 'Funda de almohada rayada de 600 hilos',
    desc: 'Fundas de algodón rayadas, varios colores disponibles.',
    price: '6.500',
    emoji: '🌼',
    badges: 'promo',
    indications:'',
    images: [
      'assets/products/fundas-almohadas-rayadas.jpg',
      'assets/products/fundas-almohadas-rayadas-2.jpg',
    ],
  },
  {
    id: 8,
    cat: 'baño',
    name: 'Cortina de baño, tela bambú con ganchos metálicos',
    desc: 'Cortina de baño de tela bambú + Ganchos metálicos. Diseños exclusivos.',
    price: '27.000',
    emoji: '🏖️',
    indications: 'Lavar con agua tibia a menos de 30° con detergente sin iones, secar con maquina a menos de 30°',
    badges: 'new',
    indications:'',
    images: [
      'assets/products/cortina-bano-bambu.jpg',
      'assets/products/cortina-bano-bambu-2.jpg',
      'assets/products/cortina-bano-bambu-3.jpg', 
    ],
  },
  // ---------- Cocina ----------
  {
    id: 9,
    cat: 'cocina',
    name: 'Delantal de cocina',
    desc: 'Delantal de cocina resistente y lavable. Varios diseños y colores disponibles.',
    price: '19.000',
    emoji: '👨‍🍳',
    badge: 'new',
    indications:'',
    images: [
      'assets/products/delantal-cocina.jpg',
      'assets/products/delantal-cocina-2.jpg',
      'assets/products/delantal-cocina-3.jpg',
      'assets/products/delantal-cocina-4.jpg',
    ],
  },
  {
    id: 10,
    cat: 'cocina',
    name: 'Mantel antimanchas',
    desc: 'Mantel antimanchas, diseño 100% de poliester, fácil de lavar',
    price: '20.000',
    emoji: '🧺',
    badge: 'new',
    indications:'',
    images: [
      'assets/products/mantel-antimanchas.jpg',
      'assets/products/mantel-antimanchas-2.jpg',
      'assets/products/mantel-antimanchas-3.jpg', 
    ],
  },
    {
    id: 16,
    cat: 'cocina',
    name: 'Repasadores de cocina colgantes',
    desc: 'Repasadores colgantes, hermosos diseños de frutas ideales para decorar tu cocina. 100% algodón.',
    price: '6.000',
    emoji: '🧺',
    badge: 'new',
    indications:'',
    images: [
      'assets/products/repasadores-frutas.jpg',
      'assets/products/repasadores-frutas-2.jpg',
      'assets/products/repasadores-frutas-3.jpg', 
      'assets/products/repasadores-frutas-4.jpg',
    ],
  },
  // ---------- Línea Infantil ----------
  {
    id: 11,
    cat: 'lineainfantil',
    name: 'Sábanas infantiles en mochila — Línea Disney',
    desc: 'Juego de sábanas infantiles en mochila. Diseños Disney. Ideal para regalo.',
    price: '30.000',
    emoji: '🧸',
    badge: 'new',
    indications:'', 
    images: [
      'assets/products/sabanas-infantiles.jpg',
      'assets/products/sabanas-infantiles-2.jpg',
    ],
  },
  {
    id: 12,
    cat: 'lineainfantil',
    name: 'Frazadas Flannel infantiles',
    desc: 'Frazadas de flannel suaves y abrigadas. Varios diseños y colores para los más chiquitos.',
    price: '22.000',
    emoji: '🌟',
    badge: 'new',
    indications:'',
    images: [
      'assets/products/sabanas-infantiles-flannel.jpg',
      'assets/products/sabanas-infantiles-flannel-2.jpg',
      'assets/products/sabanas-infantiles-flannel-3.jpg',
      'assets/products/sabanas-infantiles-flannel-4.jpg',
      'assets/products/sabanas-infantiles-flannel-5.jpg',
    ],
  },
];